### ISSUE TITLE
Delay in Relay Switch

### ISSUE THREAD

**Issue by Paulf007** [jschaeke/arduinoHouse#2]
Hello , first off well done on this excellent work done!
One thing that I have noticed is that there is a delay between the switching the relay after receiving the "toggle" command (2). It seems to be about 500 ms or so but thats just guessing on the time.
Is this normal?

**Comment by jschaeke** [comment]
Yes I had added it because my first version without it broke the relays on the board as the Somfy window motor need some timeout between up and down toggle. You can reduce them easily by lowering the numbers (to 1 or 0 ms):
https://github.com/jschaeke/arduinoHouse/blob/master/arduinoHouse/mqttRelayDelays/mqttRelayDelays.ino#L97
